name: deploy

on:
  push:
    branches:
      - master
    tags:
      - v4.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.469'
      - name: Deploy to clojars
        run: make build
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
